/**
 * Agent-vs-human labelling.
 *
 * The protocol's first choice was the AIDev dataset, whose provenance labels are the
 * reason it is worth using. AIDev is distributed via Hugging Face, which this environment
 * cannot reach, so provenance is recovered from the git record instead.
 *
 * BE HONEST ABOUT WHAT THIS LABEL MEANS. It is weaker than AIDev's, in a specific and
 * reportable way:
 *
 *   bot-author    — the commit author IS an agent account (copilot-swe-agent, open-swe[bot],
 *                   cursor[bot], devin-ai-integration). This is genuine agent AUTHORSHIP and
 *                   is the closest equivalent to an AIDev label.
 *   agent-trailer — a `Co-authored-by:` line naming an agent. This attests agent ASSISTANCE.
 *                   A human may have driven, reviewed and rewritten the change.
 *   agent-footer  — a "Generated with Claude Code" style footer. Same caveat.
 *
 * Every PR records which of these fired and the literal matched string, so the analysis can
 * be re-cut on bot-author alone. If the agent-vs-human contrast only holds on the weaker
 * evidence tiers, that is a finding about the label, not about agents, and the writeup has
 * to say so. Reporting the pooled number without the breakdown would overclaim.
 *
 * DIRECTION OF BIAS: trailer-attested PRs are, if anything, the ones where a human was
 * engaged enough to keep the attribution. So this labelling likely UNDERSTATES any
 * agent-vs-human difference rather than manufacturing one.
 */

import type { Provenance, ProvenanceEvidence } from './types.js';

/** Author accounts that ARE coding agents. */
const BOT_AUTHOR =
  /(devin-ai-integration|cursoragent|cursor\[bot\]|copilot-swe-agent|open-swe\[bot\]|claude\[bot\]|codex\[bot\]|google-labs-jules|jules\[bot\]|sweep-ai|codegen-sh|factory-droid|charlie-helps)/i;

/** The bare "Copilot" author account GitHub uses for Copilot-authored PRs. */
const BARE_COPILOT_AUTHOR = /^copilot$/i;

const AGENT_TRAILER = /^Co-authored-by:\s*([^<\n]*?(?:copilot|claude|devin|cursor|codex|jules|open-swe|charlie)[^<\n]*)/im;

const AGENT_FOOTER =
  /(Generated with \[?Claude Code|🤖 Generated with|Co-Authored-By:\s*Claude|generated by \[?claude|Created by Devin|devin\.ai\/sessions|cursor\.com\/agents)/i;

/**
 * Automation that is NOT a coding agent in the sense this study cares about. These open
 * mechanical PRs (version bumps, generated model profiles) with no mechanism to explain.
 * They are dropped entirely rather than labelled, so they cannot inflate either group.
 */
const NON_AGENT_AUTOMATION =
  /(dependabot|renovate|github-actions|pre-commit-ci|allcontributors|snyk-bot|imgbot|model-profile-bot|oss-model-profiles|corridor-security)/i;

export interface ProvenanceResult {
  provenance: Provenance;
  evidence: ProvenanceEvidence;
  marker: string | null;
}

export function isNonAgentAutomation(authorName: string, authorEmail: string): boolean {
  return NON_AGENT_AUTOMATION.test(authorName) || NON_AGENT_AUTOMATION.test(authorEmail);
}

export function classify(authorName: string, authorEmail: string, body: string): ProvenanceResult {
  const botAuthor = BOT_AUTHOR.exec(authorName) || BOT_AUTHOR.exec(authorEmail);
  if (botAuthor) return { provenance: 'agent', evidence: 'bot-author', marker: botAuthor[0] };

  if (BARE_COPILOT_AUTHOR.test(authorName.trim())) {
    return { provenance: 'agent', evidence: 'bot-author', marker: 'Copilot' };
  }

  const trailer = AGENT_TRAILER.exec(body);
  if (trailer) return { provenance: 'agent', evidence: 'agent-trailer', marker: trailer[1].trim().slice(0, 60) };

  const footer = AGENT_FOOTER.exec(body);
  if (footer) return { provenance: 'agent', evidence: 'agent-footer', marker: footer[0].slice(0, 60) };

  return { provenance: 'human', evidence: 'none', marker: null };
}

/**
 * Strip attribution from the record before it is scored.
 *
 * Two independent reasons, both mandatory:
 *
 *   1. LEAKAGE OF THE GROUPING VARIABLE. A record ending in "Generated with Claude Code"
 *      tells the scorer which arm the PR is in. The agent-vs-human comparison would then be
 *      partly measuring the scorer's prior about agents.
 *   2. These trailers carry no mechanism, so they are noise against the rubric either way.
 *
 * Only attribution lines are removed. Prose is never touched — including prose that
 * happens to mention an agent, since that IS content the author chose to write.
 */
export function stripAttribution(body: string): string {
  const lines = body.split('\n');
  const kept = lines.filter((l) => {
    const t = l.trim();
    if (/^(Co-authored-by|Signed-off-by|Reviewed-by|Acked-by|Tested-by|Reported-by|Suggested-by):/i.test(t)) return false;
    if (/^🤖\s*Generated with/i.test(t)) return false;
    if (/^Generated with \[?Claude Code/i.test(t)) return false;
    if (/^_?Generated by \[?Claude Code/i.test(t)) return false;
    if (/^https?:\/\/(devin\.ai\/sessions|cursor\.com\/agents)/i.test(t)) return false;
    return true;
  });
  return kept.join('\n').replace(/\n{3,}/g, '\n\n').trim();
}
