/**
 * Step 1 — extraction.
 *
 * A git clone is the whole dependency. No GitHub API, no auth, no network beyond the clone.
 * That is not a simplification, it is the point: it means the map can be generated for a
 * prospect's public repository before ever speaking to them, and it means a private-repo
 * customer can run it themselves without granting anyone access.
 *
 * PARSING, AND WHY NOT THE OBVIOUS FORMAT. The natural command is
 *
 *   git log --no-merges --numstat --format='%H%x09%an%x09%ae%x09%ad%x09%s%x09%b'
 *
 * and it is unparseable. `%b` is a commit body: it contains newlines, and frequently contains
 * tabs. Splitting on either loses commits, and it loses them non-randomly — the ones with long
 * structured bodies, which are exactly the commits the record dimension is about. So the
 * format uses ASCII record (0x1e) and unit (0x1f) separators, which git will not emit from
 * commit content on any repository that is not actively attacking this tool.
 *
 * THE ANALYSIS DATE IS HEAD'S AUTHOR DATE, NOT WALL CLOCK. Two reasons, both load-bearing:
 * the same clone must produce the same map tomorrow, and the retrospective validation in
 * validate.ts works by rebuilding the map "as of" a past date, which is only coherent if
 * every date-relative measure keys off a parameter rather than `Date.now()`.
 */

import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import type { Commit } from './types.js';

const exec = promisify(execFile);

const REC = '\x1e';
const UNIT = '\x1f';

/** Buffer ceiling for `git log` on a large repository. Airflow's full history is ~200MB. */
const MAX_BUFFER = 1024 * 1024 * 1024;

export interface LogOpts {
  /** Path to the clone. */
  repo: string;
  /** Only commits strictly before this epoch ms. Used by the retrospective validation. */
  before?: number;
  /** Only commits at or after this epoch ms. */
  after?: number;
}

/**
 * Agent attribution in a commit message.
 *
 * Matches the study's provenance detection, which is deliberate: the two artifacts should
 * disagree about nothing. This is a CONTEXT signal and never a quality signal — it tells a
 * reader how much of a region arrived through an agent, which they will care about whether or
 * not anyone editorialises about it.
 */
const AGENT_TRAILER =
  /^\s*co-authored-by:\s*.*(claude|copilot|cursor|devin|codex|aider|sweep|gpt-engineer|openhands|bot@|\[bot\])/im;
const AGENT_FOOTER =
  /(generated with \[?claude code|🤖 generated with|co-authored-by: claude|created by cursor|generated by (devin|copilot))/i;

export function hasAgentTrailer(message: string): boolean {
  return AGENT_TRAILER.test(message) || AGENT_FOOTER.test(message);
}

/**
 * numstat renames.
 *
 * git emits three shapes for a rename: `old => new`, `dir/{a => b}/file`, and `{a => b}/file`.
 * All three are resolved to the NEW path, because the map describes the tree as it stands.
 * File-level history would need `--follow`, which handles one path at a time and guesses;
 * this is one of the two reasons the unit of analysis is a directory. See regions.ts.
 */
export function resolveRenamePath(raw: string): string {
  const brace = raw.match(/^(.*)\{(.*) => (.*)\}(.*)$/);
  if (brace) {
    const [, pre = '', , to = '', post = ''] = brace;
    return `${pre}${to}${post}`.replace(/\/{2,}/g, '/');
  }
  const arrow = raw.match(/^(.*) => (.*)$/);
  if (arrow) return arrow[2] ?? raw;
  return raw;
}

export function parseLog(raw: string): Commit[] {
  const out: Commit[] = [];
  for (const chunk of raw.split(REC)) {
    if (!chunk.trim()) continue;
    // The header is the first six unit-separated fields; everything after the sixth is the
    // numstat block, which git appends after the format string.
    const parts = chunk.split(UNIT);
    if (parts.length < 6) continue;
    const [sha = '', authorName = '', authorEmail = '', dateIso = '', subject = ''] = parts;
    const rest = parts.slice(5).join(UNIT);

    // The body runs until the numstat block. numstat lines are `<added>\t<deleted>\t<path>`
    // with `-` for binary, so the first line matching that shape ends the body.
    const lines = rest.split('\n');
    const bodyLines: string[] = [];
    const files: Commit['files'] = [];
    let inStat = false;
    for (const line of lines) {
      const m = line.match(/^(\d+|-)\t(\d+|-)\t(.+)$/);
      if (m) {
        inStat = true;
        const [, a = '0', d = '0', p = ''] = m;
        // Binary files report `-`. They have no lines to attribute, but they are still a
        // touch on the region, so they are kept with zero weight rather than dropped.
        files.push({
          path: resolveRenamePath(p),
          added: a === '-' ? 0 : Number(a),
          deleted: d === '-' ? 0 : Number(d),
        });
      } else if (!inStat) {
        bodyLines.push(line);
      }
    }

    const at = Date.parse(dateIso);
    if (!Number.isFinite(at)) continue;

    const body = bodyLines.join('\n').trim();
    out.push({
      sha,
      authorName,
      authorEmail,
      at,
      subject,
      body,
      files,
      agentTrailer: hasAgentTrailer(`${subject}\n${body}`),
      bot: false, // set by identity.ts, which owns every judgement about who
    });
  }
  return out;
}

export async function readLog(opts: LogOpts): Promise<Commit[]> {
  const args = [
    'log',
    '--no-merges',
    '--numstat',
    '--date=iso-strict',
    `--format=${REC}%H${UNIT}%an${UNIT}%ae${UNIT}%ad${UNIT}%s${UNIT}%b`,
  ];
  // `--since-as-filter`, NOT `--after`. `--after` stops TRAVERSAL at the first out-of-range
  // commit rather than filtering, so a single back-dated commit — an imported history, a
  // clock-skewed CI box, `git commit --date`, a dormant branch merged late — silently deletes
  // everything behind it with no error and no diagnostic. Demonstrated on a three-commit repo:
  // with one commit dated 2019 between two 2024 ones, `--after=2023-01-01` returns one commit
  // and `--since-as-filter=2023-01-01` returns both of the 2024 ones.
  //
  // Both flags also test the COMMITTER date, while everything downstream uses the AUTHOR date
  // (%ad). They are therefore a cheap prefilter only; the authoritative author-date bounds are
  // enforced in filterCommits, which is what makes `asOf` mean what validate.ts needs it to.
  if (opts.before) args.push(`--before=${new Date(opts.before).toISOString()}`);
  if (opts.after) args.push(`--since-as-filter=${new Date(opts.after).toISOString()}`);

  const { stdout } = await exec('git', args, { cwd: opts.repo, maxBuffer: MAX_BUFFER });
  return parseLog(stdout);
}

/** HEAD's SHA and author date. The map is always stamped with the commit it describes. */
export async function readHead(repo: string): Promise<{ sha: string; at: number }> {
  const { stdout } = await exec('git', ['log', '-1', '--date=iso-strict', '--format=%H%x1f%ad'], {
    cwd: repo,
    maxBuffer: 1024 * 1024,
  });
  const [sha = '', date = ''] = stdout.trim().split(UNIT);
  return { sha, at: Date.parse(date) };
}

/** `owner/name` from the origin remote, falling back to the directory name. */
export async function readRepoName(repo: string): Promise<string> {
  try {
    const { stdout } = await exec('git', ['remote', 'get-url', 'origin'], { cwd: repo });
    const m = stdout.trim().match(/[:/]([^/:]+\/[^/]+?)(\.git)?$/);
    if (m?.[1]) return m[1];
  } catch {
    // No remote is normal for a local-only clone; the directory name is a fine label.
  }
  return repo.replace(/\/+$/, '').split('/').pop() ?? repo;
}

/**
 * Every (name, email) pair in the FULL history, with no `--numstat`.
 *
 * Identity clustering must see the whole history even though the metrics only need the window.
 * Clustering unions transitively on display name, so a commit older than the window can be the
 * only bridge between two in-window aliases of one person — and losing that bridge splits one
 * contributor into two, which invents a bus factor and reports it as risk. Measured on a
 * synthetic repo with the in-window edit set held identical: orphanedShare moved 0.00 to 0.50
 * and the region flipped from unflagged to flagged.
 *
 * This is cheap precisely because it omits `--numstat` — the diff walk is what makes the main
 * log slow, and this call reads only commit headers.
 */
export async function readAuthorRoster(
  repo: string,
  before?: number,
  withDates = false
): Promise<{ name: string; email: string; at: number }[]> {
  const args = [
    'log',
    '--no-merges',
    '--date=iso-strict',
    `--format=%an${UNIT}%ae${UNIT}%ad`,
  ];
  if (before) args.push(`--before=${new Date(before).toISOString()}`);
  const { stdout } = await exec('git', args, { cwd: repo, maxBuffer: MAX_BUFFER });
  const out: { name: string; email: string; at: number }[] = [];
  for (const line of stdout.split('\n')) {
    if (!line) continue;
    const [name = '', email = '', date = ''] = line.split(UNIT);
    const at = withDates ? Date.parse(date) : 0;
    if (withDates && !Number.isFinite(at)) continue;
    out.push({ name, email, at });
  }
  return out;
}

/**
 * Every path in the tree at a given commit.
 *
 * Needed because a region can be built entirely from commits to files that NO LONGER EXIST.
 * A directory deleted two years ago still has history inside the window, so it is admitted as a
 * row, scores whatever its long-departed authors scored, and then — being deleted — receives no
 * further commits, which the validation reads as a correct prediction of dormancy. It is not a
 * prediction. It is arithmetic about a directory that is gone.
 */
export async function readTreePaths(repo: string, ref = 'HEAD'): Promise<Set<string>> {
  const { stdout } = await exec('git', ['ls-tree', '-r', '--name-only', ref], {
    cwd: repo,
    maxBuffer: MAX_BUFFER,
  });
  return new Set(stdout.split('\n').filter(Boolean));
}

/** The unified diff for one commit, used only by the record-coverage stage. */
export async function readCommitDiff(repo: string, sha: string): Promise<string> {
  const { stdout } = await exec(
    'git',
    ['show', '--format=', '--unified=3', '--no-color', sha],
    { cwd: repo, maxBuffer: 256 * 1024 * 1024 }
  );
  return stdout;
}
